baseURL = 'https://otakufreak13.github.io'
languageCode = 'en-us'
title = 'Portfolio for Björn'

theme = "gokarna"
defaultContentLanguage = "en"
enableEmoji = true
# Automatically generate robots.txt
enableRobotsTXT = true


[params]
  footer = "Björn Johansson"
  description = "Welcome! I'm a C++ programmer with an education in Game and Software Engineering"
  avatarURL = "/images/SelfieHiking.jpg"
  avatarSize = "size-m"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.css" integrity="sha384-6LkG2wmY8FK9E0vU9OOr8UvLwsaqUg9SETfpq4uTCN1agNe8HRdE9ABlk+fVx6gZ" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.js" integrity="sha384-31El76TwmbHj4rF9DyLsygbq6xoIobG0W+jqXim+a3dU9W53tdH3A/ngRPxOzzaB" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>
  """
  
  socialIcons = [
   # {name = "twitter", url = "https://example.com"},
    {name = "linkedin", url = "https://www.linkedin.com/in/bj%C3%B6rn-johansson-3b20371a8/"},
    {name = "github", url = "https://github.com/otakufreak13"},
    {name = "Resume", url = "{{ .Site.BaseURL }}/docs/cv_bj.pdf"},
   # {name = "stackoverflow", url = "https://example.com"},
   # {name = "dribbble", url = "https://example.com"},
   # {name = "instagram", url = "https://example.com"},
   # {name = "twitch", url = "https://example.com"},
  ]
  metaKeywords = ["portfolio", "programmer", "gamedev"]

  showpostsonhomepage = "recent"

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    #identifier = "posts"

    #url = "/posts/"

#    identifier = "resume"
#
#    url = "/docs/cv_bj.pdf"
#    
#    # You can add extra information before the name (HTML format is supported), such as icons
#    pre = ""
#
#    # You can add extra information after the name (HTML format is supported), such as icons
#    post = ""
#
#    # Display name
#    name = "Resume"
#
#    # Weights are used to determine the ordering
#    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Project Tags"
    url = "/tags/"
    weight = 2
    
  [[menu.main]]
    #identifier = "linkedin"
    #url = "https://www.linkedin.com/in/bj%C3%B6rn-johansson-3b20371a8/"
    #weight = 4
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/OtakuFreak13/OtakuFreakHugoSite"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    #pre = "<span data-feather='linkedin'></span>"